name:                proxy-tester
version:             0.1.0.0
github:              "githubuser/proxy-tester"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/proxy-tester#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  dependencies:
  - vt-utils

executables:
  proxy-tester-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
      - condition: True
        ghc-options:
        - -fno-specialise
        - -fmax-simplifier-iterations=0
        - -fsimplifier-phases=0
      - condition: os(linux)
        ghc-options:
        - -pgml
        - g++
        - "-optl-Wl,--allow-multiple-definition"
        - "-optl-Wl,--whole-archive"
        - "-optl-Wl,-Bstatic"
        - "-optl-Wl,-lfltkc"
        - "-optl-Wl,-Bdynamic"
        - "-optl-Wl,--no-whole-archive"
      - condition: os(windows)
        ghc-options:
        - -optl-mwindows
        - -pgml
        - g++
        - "-optl-Wl,--allow-multiple-definition"
        - "-optl-Wl,--whole-archive"
        - "-optl-Wl,-Bstatic"
        - "-optl-Wl,-lfltkc"
        - "-optl-Wl,-Bdynamic"
        - "-optl-Wl,--no-whole-archive"
      - condition: os(darwin)
        ghc-options:
        - "-optl-Wl,-lfltkc"
    dependencies:
    - fltkhs
    - vt-utils
    - proxy-tester

tests:
  proxy-tester-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proxy-tester
